Optional wildcards
lukeed/regexparam pull request #25
Opened 2022-09-27 09:45 UTC by benmerckx

Closes #24

2023-09-08 08:50 UTC, molefrog commented
Hi @lukeed, just wanted to ask to take a brief look at this. 
This is the only thing that blocks us from switching to regexparam in https://github.com/molefrog/wouter.

2023-12-03 20:41 UTC, lukeed requested changes

2023-12-03 20:41 UTC, lukeed commented on src/index.js
> +			pattern += o ? '(?:/(.*))?' : '/(.*)';
```suggestion
			pattern += tmp[1] === '?' ? '(?:/(.*))?' : '/(.*)';
```

2023-12-03 20:41 UTC, lukeed commented on src/index.js
> +			o = tmp[1] === '?';
```suggestion
```

2023-12-03 21:18 UTC, lukeed approved these changes
Thank you for this :) It's a breaking change due to how the `"/books/*?"` pattern will now match `"/books"` (shown in test), but I think it's a change worth having.

Cutting this as a 3.0 release

2023-12-03 21:18 UTC, merged

2023-12-09 10:18 UTC, molefrog commented
@lukeed Thank you! We added it back as a dependency and it works well. https://github.com/molefrog/wouter/pull/395